// mocinno/frontend/src/lib/components/nav.svelte
<script lang="ts">
	import NestLogo from '$lib/components/nestlogo.svelte';
	import Menu from '@lucide/svelte/icons/menu';
	import Terminal from '@lucide/svelte/icons/terminal';
	import House from '@lucide/svelte/icons/house';
	import ToolCase from '@lucide/svelte/icons/tool-case';
	import Book from '@lucide/svelte/icons/book';
	import Server from '@lucide/svelte/icons/server';
	import { resolve } from '$app/paths';
	import { page } from '$app/state';
	import authClient from '$lib/auth';
	import type { Component } from 'svelte';
	import { goto } from '$app/navigation';

	interface NavItem {
		href: string;
		icon: Component;
		class: string;
		text: string;
	}

	let isOpen = $state(false);

	const navItems: NavItem[] = [
		{
			href: resolve('/'),
			icon: House,
			class: 'text-2xl md:mr-2',
			text: 'Home'
		},
		{
			href: resolve('/projects'),
			icon: ToolCase,
			class: 'text-2xl md:mr-2',
			text: 'Projects'
		},
		{
			href: 'https://guides.hackclub.app/',
			icon: Book,
			class: 'text-2xl md:mr-2',
			text: 'Wiki'
		},
		{
			href: 'https://status.hackclub.app/',
			icon: Server,
			class: 'text-2xl md:mr-2',
			text: 'Status'
		}
	];

	let { user }: { user: typeof authClient.$Infer.Session.user | null } = $props();
</script>

<nav
	class="sticky top-0 z-50 flex items-center justify-between border-b-2 border-violet-950 bg-[#03001c] px-4 py-4 transition-all duration-150 ease-out md:relative lg:border-transparent lg:bg-transparent lg:px-16 lg:py-8 lg:max-tabletx:px-8"
>
	<div class="right-0 flex items-end gap-x-4 lg:hidden">
		<a href={resolve('/')} class="transition-transform hover:scale-105">
			<NestLogo width={70} height={70} class="text-foreground" />
		</a>
	</div>

	<div class="hidden items-end gap-x-4 font-dm-mono md:gap-x-9 lg:flex">
		<a href={resolve('/')} class="shrink-0 transition-transform hover:scale-105">
			<NestLogo width={85} height={85} class="text-foreground" />
		</a>
		{#each navItems as item (item.href)}
			<a
				href={/* eslint-disable-line */ item.href}
				class="group flex items-center text-xl font-light transition-colors hover:text-primary 2xl:text-2xl"
			>
				<span class="mr-2 transition-transform group-hover:scale-110"
					><item.icon class={item.class} /></span
				>
				<span class="border-b-2 border-transparent group-hover:border-primary">
					{item.text}
				</span>
			</a>
		{/each}
	</div>

	<div class="flex justify-end bg-[#03001c] shadow-lg lg:hidden">
		<button class="z-50" onclick={() => (isOpen = !isOpen)}>
			<Menu class="text-lg" />
		</button>

		<div
			class={`${isOpen ? 'absolute' : 'hidden'} right-0 z-40 mt-10 h-screen w-screen gap-y-10 border-t-2 border-violet-950 p-5 backdrop-blur-3xl backdrop-brightness-50`}
		>
			<button onclick={() => (isOpen = false)}>
				{#each navItems as item (item.href)}
					<a
						href={/* eslint-disable-line */ item.href}
						class="group ml-5 flex items-center py-5 text-xl font-light transition-colors hover:text-primary"
					>
						<span class="mr-2 transition-transform group-hover:scale-110"
							><item.icon class={item.class} /></span
						>
						<span class="border-b-2 border-transparent group-hover:border-primary">
							{item.text}
						</span>
					</a>
				{/each}
			</button>
		</div>
	</div>

	<div
		class="absolute right-8 hidden animate-fadeInDown items-center justify-end gap-x-4 py-4 opacity-0 lg:flex lg:py-8"
	>
		<button
			onclick={() => {
				if (user && !page.url.searchParams.get('invite')) {
					goto(resolve('/dashboard'));
				} else {
					authClient.signIn.oauth2({
						providerId: 'hackclub',
						callbackURL: '/dashboard',
						additionalData: {
							invite_code: page.url.searchParams.get('invite')
						}
					});
				}
			}}
			class="group flex cursor-pointer items-center gap-x-2 rounded-lg border-2 border-primary px-4 py-2 font-dm-mono text-sm font-medium transition-all duration-200 hover:scale-105 active:scale-95 tabletx:text-base 2xl:text-xl"
		>
			<Terminal /><span>Dashboard</span>
		</button>
	</div>
</nav>

// website/components/nav.tsx
import Image from "next/image";
import Link from "next/link";
import { useState, useEffect } from "react";
import {
  FaHome,
  FaServer,
  FaBook,
  FaTools,
  FaTerminal,
  FaCode,
  FaGithub,
  FaBars,
  FaTimes
} from "react-icons/fa";

interface NavItem {
  href: string;
  icon: JSX.Element;
  text: string;
}


const navItems: NavItem[] = [
  {
    href: "/",
    icon: <FaHome className="text-2xl md:mr-2" />,
    text: "Home",
  },
  {
    href: "/projects",
    icon: <FaTools className="text-xl md:mr-2" />,
    text: "Projects",
  },
  {
    href: "https://guides.hackclub.app/",
    icon: <FaBook className="text-xl md:mr-2" />,
    text: "Wiki",
  },
  {
    href: "https://status.hackclub.app/",
    icon: <FaServer className="text-xl md:mr-2" />,
    text: "Status",
  },
  {
    href: "https://github.com/hackclub/nest/",
    icon: <FaGithub className="text-xl md:mr-2" />,
    text: "GitHub",
  },
];

const NavLink: React.FC<NavItem & { className?: string }> = ({
  href,
  icon,
  text,
  className,
}) => (
  <Link
    href={href}
    className={`group flex items-center text-xl font-light transition-colors hover:text-HCPurpleText ${className}`}
  >
    <span className="transition-transform group-hover:scale-110 mr-2">{icon}</span>
    <span className="border-b-2 border-transparent group-hover:border-HCPurpleText">
      {text}
    </span>
  </Link>
);

const ActionButton: React.FC<{
  href: string;
  icon: JSX.Element;
  text: string;
  primary?: boolean;
}> = ({ href, icon, text, primary }) => (
  <Link
    href={href}
    className={`group flex items-center gap-x-2 rounded-lg border-2 border-HCPurple px-4 py-2 font-dm-mono text-base font-medium transition-all duration-300 hover:scale-105 active:scale-95 2xl:text-xl ${
      primary
        ? "bg-HCPurple text-white"
        : "text-HCPurpleText hover:bg-HCPurple hover:text-white"
    }`}
  >
    {icon}
    <span>{text}</span>
  </Link>
);


export default function Nav() {
  const [isOpen, setIsOpen] = useState(false);

  useEffect(() => {
    document.body.style.overflow = isOpen ? "hidden" : "unset";
  }, [isOpen]);
  
  return (
    <nav className="sticky bg-[#03001c] top-0 z-50 w-full md:relative flex items-center justify-between border-b-2 border-violet-950 px-4 py-4 lg:border-transparent md:bg-transparent lg:px-16">
      <div className="flex items-end right-0 gap-x-4 md:hidden">
        <Link href="/" className="transition-transform hover:scale-105">
          <Image src="/nest.svg" alt="Nest logo" width={70} height={70} />
        </Link>
      </div>

      <div className="hidden items-end justify-center gap-x-4 font-dm-mono text-white md:gap-x-9 md:flex ">
        <Link
          href="/"
          className="flex-shrink-0 transition-transform hover:scale-105"
        >
          <Image src="/nest.svg" alt="Nest logo" width={85} height={85} />
        </Link>
        {navItems.map((item, index) => (
          <NavLink key={index} {...item} className="2xl:text-2xl" />
        ))}
      </div>

      <div className="flex md:hidden justify-end bg-[#03001c] shadow-lg">
      <button className = "z-50" onClick ={() => setIsOpen(!isOpen)}>
         {isOpen ? (
          <FaTimes className="text-xl "/>
            ) : (
          <FaBars className="text-xl "/>)}
        </button>

        <div className = {`${isOpen ? "absolute": "hidden"} z-40 gap-y-10 w-screen h-screen mt-10 p-5 right-0 border-t-2 border-violet-950 backdrop-blur-3xl backdrop-brightness-50 transition-opacity`}>
        <button onClick={() => setIsOpen(false)}>
            {navItems.map((item, index) => (
             <NavLink key={index} {...item} className="text-white ml-5 py-5" /> ))}
          </button>
        </div>
      </div>

      <div className="hidden translate-y-[-20px] animate-[fadeInDown_0.5s_ease-out_forwards] items-center justify-end gap-x-6 opacity-0 lg:flex">
        <ActionButton
          href="https://guides.hackclub.app/index.php/Quickstart"
          icon={<FaCode className="text-xl" />}
          text="Join Nest!"
          primary
        />
        <ActionButton
          href="https://identity.hackclub.app"
          icon={<FaTerminal className="text-xl" />}
          text="Login"
        />
      </div>
    </nav>
  );
}
